### ISSUE TITLE
UI timezone not adapted

### ISSUE THREAD

**Issue by Timo-Linde** [moeiscool/Shinobi#99]
![shinobi timezone problem](https://cloud.githubusercontent.com/assets/9592381/24100073/b7b6e5fc-0d72-11e7-8b82-45d4cd7f830a.JPG)

conf.json
` "utcOffset":"+0100"`

**Comment by Bonnee** [comment]
I have a similar issue: The recordings' file name is right with my timezone, but the one reported by the UI doesn't consider the offset: it reports a time with 0 offset (e.g. 2017-03-20T15:45:01.000Z while the filename is 2017-03-20T16-45-01.mp4). Querying the db, the time seems fine. So it's definitely an UI issue. The clock in the dash is right tho.

I too have the offset set to +0100

**Comment by moeiscool** [comment]
hmm i thought i fixed the timestamp thing, guess not. No errors appear in `pm2 logs`? is daylight savings correctly set on the machine you have shinobi installed?

**Comment by Bonnee** [comment]
Yes, I have DST set correctly and no, no errors pop up in the logs

**Comment by Timo-Linde** [comment]
No errors in `pm2 logs`
OS: Debian GNU/Linux 8 (64 Bit)
Daylight saving time seems to work properly
![dst](https://cloud.githubusercontent.com/assets/9592381/24147412/5a616e9a-0e3a-11e7-84b8-53bd28e10f91.JPG)

**Comment by moeiscool** [comment]
Any errors in your browser console when trying to delete? Can you paste the last few console outputs when doing the delete please.

**Comment by Bonnee** [comment]
I get no output at all when deleting

**Comment by moeiscool** [comment]
i mean in browser console on the client side. Not terminal.

**Comment by Bonnee** [comment]
Yes, I get no errors from anywhere. In fact I never noticed this bug until I came across this issue

**Comment by moeiscool** [comment]
what outputs do you get? can you paste those objects here? it should return `video_delete` in one of them

**Comment by Timo-Linde** [comment]
![delete console](https://cloud.githubusercontent.com/assets/9592381/24198720/441b7d9c-0f07-11e7-83ac-98d74b8e268b.JPG)

**Comment by moeiscool** [comment]
sorry i havent got back to this issue. i have been working on a few things in motion. ah yah not video_delete but will look into it that output is helpful.

**Comment by moeiscool** [comment]
i think i fixed this and i haven't run into this issue for a while now. going to close unless you are experiencing this on the latest master or dev.

**Comment by Bonnee** [comment]
I still have this issue, and after the daylight change the delay has increased to 2 hours

**Comment by moeiscool** [comment]
is your server's time and sql time correct? I actually experienced this yesterday and the fix was correcting the offset in `my.cnf` for sql.
I actually experienced this yesterday and the fix was correcting the offset in `my.cnf` for sql.

**Comment by moeiscool** [comment]
newest commit fixes this
